apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-python
spec:
  replicas: 10
  selector:
    matchLabels:
      app: python
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: cloudsiksha/pythonapp:v2
        ports:
        - containerPort: 80