apiVersion: v1
kind: Service
metadata:
  name: mysample-svc
  labels:
    app: mysample-world
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: mysample-world