apiVersion: v1
kind: Pod
metadata:
  name: mysample-pod
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: mysample-ctr
    image: nigelpoulton/k8sbook:latest
    ports:
    - containerPort: 8080