apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    app: python
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: python
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "python"
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: cloudsiksha/pythonapp:v1
        ports:
        - containerPort: 80
          name: web